version: "3.9"

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: restaurant_crm_app
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - db
      - redis
    networks:
      - backend

  worker:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: restaurant_crm_worker
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    volumes:
      - ./:/var/www/html
    depends_on:
      - app
      - redis
    networks:
      - backend

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: restaurant_crm_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - app
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: restaurant_crm_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: restaurant_crm
      MYSQL_USER: app
      MYSQL_PASSWORD: appsecret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: restaurant_crm_redis
    ports:
      - "6380:6379"
    networks:
      - backend

  echo:
    image: node:20-alpine
    container_name: restaurant_crm_echo
    working_dir: /var/www/html
    command: sh -lc "npm ci --include=dev && npx laravel-echo-server start --config laravel-echo-server.json"
    volumes:
      - ./:/var/www/html
    ports:
      - "6001:6001"
    depends_on:
      - redis
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
